resource:
  tasks: http://localhost:8080/v1/tasks
server:
  port: 8081
  session:
   tracking-modes: cookie

---

spring:
  profiles: container
  application:
    name: task-client-service
resource:
  tasks: http://${API_HOST}:${API_PORT}/v1/tasks
server:
  port: ${CLIENT_PORT}
  session:
    tracking-modes: cookie